#! /usr/bin/env python3

"""Display configuration constants for e-ink display layout."""

# Display dimensions
DISPLAY_WIDTH = 296
DISPLAY_HEIGHT = 128

# Grid layout - vertical dividers
VERTICAL_LINE_1 = 100
VERTICAL_LINE_2 = 201

# Grid layout - horizontal dividers
HORIZONTAL_LINE_MAIN = 110

# Section boundaries
SECTION_CPU_LEFT = 0
SECTION_CPU_RIGHT = 100
SECTION_NVME_LEFT = 100
SECTION_NVME_RIGHT = 201
SECTION_TRAFFIC_LEFT = 201
SECTION_TRAFFIC_RIGHT = 296

# CPU section coordinates
CPU_LABEL_Y = 0
CPU_LINE_Y = 10
CPU_ICON_X = 10
CPU_ICON_Y_LOAD = 12
CPU_ICON_Y_TEMP = 42
CPU_VALUE_X = 40
CPU_VALUE_Y_LOAD = 12
CPU_VALUE_Y_TEMP = 42

# Memory section coordinates
MEM_LABEL_X = 1
MEM_LABEL_Y = 67
MEM_LINE_Y = 76
MEM_ICON_X = 10
MEM_ICON_Y = 80
MEM_VALUE_X = 40
MEM_VALUE_Y = 80

# NVMe section coordinates
NVME_LABEL_X = 102
NVME_LABEL_Y = 0
NVME_LINE_Y = 10
NVME_ICON_X = 108
NVME_ICON_Y_DISK = 12
NVME_ICON_Y_TEMP = 42
NVME_VALUE_X = 138
NVME_VALUE_Y_DISK = 12
NVME_VALUE_Y_TEMP = 42

# Fan section coordinates
FAN_LABEL_X = 102
FAN_LABEL_Y = 67
FAN_LINE_Y = 76
FAN_ICON_X = 108
FAN_ICON_Y = 80
FAN_VALUE_X = 138
FAN_VALUE_Y = 80

# Updates section coordinates
APT_LABEL_X = 203
APT_LABEL_Y = 67
APT_LINE_Y = 76
APT_VALUE_X = 214
APT_VALUE_Y = 80

# Network status section coordinates
NET_LABEL_X = 250
NET_LABEL_Y = 67
NET_LINE_X = 249
NET_LINE_Y = 76
NET_ICON_X = 260
NET_ICON_Y = 80

# Traffic section coordinates
TRAFFIC_DOWN_LABEL_X = 203
TRAFFIC_DOWN_LABEL_Y = 0
TRAFFIC_DOWN_LINE_Y = 10
TRAFFIC_DOWN_ICON_X = 208
TRAFFIC_DOWN_ICON_Y = 10
TRAFFIC_DOWN_VALUE_X = 233
TRAFFIC_DOWN_VALUE_Y = 14
TRAFFIC_DOWN_UNIT_X = 263
TRAFFIC_DOWN_UNIT_Y = 0

TRAFFIC_UP_LABEL_X = 203
TRAFFIC_UP_LABEL_Y = 33
TRAFFIC_UP_LINE_Y = 43
TRAFFIC_UP_ICON_X = 208
TRAFFIC_UP_ICON_Y = 44
TRAFFIC_UP_VALUE_X = 233
TRAFFIC_UP_VALUE_Y = 48
TRAFFIC_UP_UNIT_X = 263
TRAFFIC_UP_UNIT_Y = 33

# Bottom bar coordinates
IP_ICON_X = 5
IP_ICON_Y = 110
IP_VALUE_X = 20
IP_VALUE_Y = 110

SIGNAL_ICON_X = 125
SIGNAL_ICON_Y = 110
SIGNAL_VALUE_X = 140
SIGNAL_VALUE_Y = 110

UPTIME_ICON_X = 205
UPTIME_ICON_Y = 110
UPTIME_VALUE_X = 220
UPTIME_VALUE_Y = 110

# Unicode icons
ICON_CPU = "\ue30d"
ICON_TEMPERATURE = "\ue1ff"
ICON_MEMORY = "\ue322"
ICON_HARD_DRIVE = "\uf7a4"
ICON_FAN = "\uf168"
ICON_NETWORK = "\ue80d"
ICON_UPTIME = "\ue923"
ICON_DOWNLOAD = "\uf090"
ICON_UPLOAD = "\uf09b"
ICON_CHECK = "\ue8e8"
ICON_WIFI_OK = "\ue2bf"
ICON_WIFI_OFF = "\uf1ca"
ICON_WIFI_SIGNAL = "\ue63e"
ICON_WIFI_NO_SIGNAL = "\ue1da"
